### ISSUE TITLE
Unable to get deprecated input object fields via introspection query

### ISSUE THREAD

**Issue by jerelmiller** [CargoSense/absinthe#1113]
### Environment

* Elixir version (elixir -v): 1.12.3
* Absinthe version (mix deps | grep absinthe): 1.6.4
* Client Framework and version (Relay, Apollo, etc): Apollo

### Expected behavior

When making an introspection query to get data about fields, I'd like to query for deprecated fields on input objects. While I am able to use the `deprecate/1` macro and the `deprecate` option on `field/3` inside an `input_object`, I am unable to query for it in the introspection query. 

I can use the built-in [introspection query](https://github.com/absinthe-graphql/absinthe/blob/master/priv/graphql/introspection.graphql) to get the data from the schema, but when I try and request `isDeprecated` on [`__InputValue`](https://github.com/absinthe-graphql/absinthe/blob/master/priv/graphql/introspection.graphql#L59-L66) or include the `includeDeprecated` arg to [`inputFields`](https://github.com/absinthe-graphql/absinthe/blob/master/priv/graphql/introspection.graphql#L43-L45), I get an error since the field doesn't exist.

Diving into the code, I do see that `isDeprecated` is not included in the [`__inputvalue` type](https://github.com/absinthe-graphql/absinthe/blob/c10eff9dd89d6220f60faf4bed672201112484d2/lib/absinthe/type/built_ins/introspection.ex#L291-L319).

I'd love to deprecate arguments to a GraphQL service I have in place, but am unable to do so.

For what its worth, it does look like this is supported in [graphql.js](https://github.com/graphql/graphql-js/blob/7da9cd31a78fa135d2a44a97d1a4dfad0858b001/src/type/introspection.ts#L401-L404)

### Actual behavior

Unable to get deprecation information on input object fields

**Comment by maartenvanvliet** [comment]
Deprecation of input values has not officially moved into the graphql spec yet, see: https://github.com/graphql/graphql-spec/pull/805 

I think the graphql.js library does have support since it's a testbed for the development of the graphql spec.

**Comment by jerelmiller** [comment]
How interesting! I didn't realize this was still just a proposal and not actually part of the spec. Thanks for pointing me in that direction!

**Comment by bjunc** [comment]
Looks like this was merged into the spec back in 08/22.
https://github.com/dchang-dchang/graphql/commit/9ef8c9b845f2329dfa64f88e02f854c0354c1d41

It'd be great if Absinthe could support this, although using the description has worked as a stop-gap.
