### ISSUE TITLE
Support passing the current target to all resolver functions

### ISSUE THREAD

**Issue by bruce** [CargoSense/absinthe#43]
Right now to get the "current object" in a resolver, you need to do something like this:

```elixir
resolve: fn
  _args, execution ->
    # do something with execution.resolution.target
end
```

Since the object is really the current scope of the schema node in question, this happens often enough, and the internals of the `Execution.t` are best considered a "private API," I think it makes sense to pass it as the first argument to the resolver, eg:

```elixir
resolve: fn
  obj, _args, _execution ->
    # do something with obj
end
```

(This would bring it generally in line with other implementations.)

Or, alternately, have some other contract we expect from resolvers.

What do you think, @benwilson512 ?

**Comment by bruce** [comment]
@benwilson512 note this might go hand-in-hand with #19

**Comment by benwilson512** [comment]
resolve: {Mod, :fun}
resolve &Mod.fun/3

**Comment by benwilson512** [comment]
Actually let's ditch the `{Mod, :fun}` version. There's an uncomfortable similarity to an archiac way of calling functions in erlang, and it makes it hard to see how one might wrap the specific resolution in pre or post resolve hooks.

**Comment by bruce** [comment]
Some notes from our last discussion:

- While getting the current scope/object is important, it's not always needed (commonly it's just the arguments)
- There are other bits of info that would also be nice to get access to:
  - The current "context," for authentication/authorization, etc
  - The child selections, for query optimization (eg, avoiding N+1)
- The fewer arguments the better. While we'd like to support these things, we don't want to do what's done in JS:

```javascript
resolve: (root, {id}, source, fieldASTs) => {
  var projections = getProjection(fieldASTs);
  return User.findById(id, projections);
}
```

Four magic arguments is just too many.

Let's plan on retaining the 2 arity approach, but restructure the second value passed to the resolution to be more user-friendly, eg (and ignore the obvious Ecto pseudocode):

```elixir
# Using the AST selections under this field to select additional data
resolve: fn %{id: id}, info ->
  found = User.projections(info.selections)
  |> Repo.get(found)
  {:ok, value}
end

# Using the current object/scope (source)
resolve: fn _, info ->
  found = User |> Repo.get(info.source.author_id)
  {:ok, found}
end
```

Draft values that would be available on `info`, above:

- `:root` - The root object (See #22)
- `:source` - The parent object (source of this field)
- `:selections` - The AST selections under this field
- `:context` - The context passed to `Absinthe.run`)
- `:schema` - The current schema in use
- `:execution` - Advanced: the full execution environment, including the document, variables, fragments, errors, execution strategy, etc

**Comment by benwilson512** [comment]
What does `execution.resolution.ast_node.selection_set.selections` look like right now?

**Comment by bruce** [comment]
That's just a guess at the path, but it would be `[Absinthe.Language.Field.t | Absinthe.Language.InlineFragment.t | Absinthe.Language.FragmentSpread.t]` I believe. For this change, we'd probably want to merge the fragments in (probably using logic extracted from `execution/resolution/selection_set.ex`) so it's just `[Absithe.Language.Field.t]`, or even go one step further and look up the matching schema fields so it would be `[Absinthe.Type.Field.t]`. I've always thought using the AST nodes was a kludge.

**Comment by benwilson512** [comment]
Agreed. I think if we supply any kind of top level selection information to users it should probably be curated from the actual AST.

**Comment by bruce** [comment]
See #49 for final implementation details.
