### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by benwilson512** [CargoSense/absinthe#51]
We should bake the post processing that's done on a schema into the schema module itself more, so that calling `.schema` is not such an expensive process.

General ideas include:

For type maps
```
def __query_type_by_name__("User"), do: MyTypeModule.user
def __query_type_by_identifier__(:user), do: MyTypeModule.user
```

Using on_definition hooks to introspect on the AST of types / queries / mutations as they're created to do the transformations then, and inject them into other functions.

Things that won't work: Unquoting the `.schema` as it currently looks somewhere. Anonymous functions can't be escaped, so they can't be unquoted into anything.

**Comment by bruce** [comment]
Handled in #53
